chromedriver=chromedriver.exe

url=https://tutorialsninja.com/demo/

myaccount=//a[@title='My Account']

register=//a[text()='Register']

firstname=input-firstname

lastname=input-lastname

email=input-email

telephone=input-telephone

password=input-password

confirm=input-confirm

policy=agree

continuebtn=//input[@value='Continue']