Desktops= xpath://a[text()='Desktops']
Mac1 = xpath://a[text()='Mac (1)']
macHeading =css:h2
sortDown = xpath://select[@id='input-sort']
Addtocart = xpath://span[text()='Add to Cart']
successMessage = css:.alert.alert-success
searchbox=xpath://input[@name='search']
searchbutton=xpath://button[@class='btn btn-default btn-lg']
resultpageheading=xpath://div[@id='content']//h1